### ISSUE TITLE
Search via ajax request when typing in cell

### ISSUE THREAD

**Issue by ryhn** [cscan/vue3-excel-editor#1]
Add field type autocomplete with url and query parameter props. it would be greate feature

**Comment by cscan** [comment]
The options prop can return a promise, you could process the select list by querying outside and return the list to the component. Is it what you want?

**Comment by ryhn** [comment]
Yes, but could be much easy via autocomplete or search type input.
:type="autocomplete|search"
:url= "/remote_url"
:url_params="{}"

Response data format could be like this;
[{label:"...", value: value}]

maybe it won't be needed if you could illustrate your suggestion on the help page.

**Comment by cscan** [comment]
The promise options only support type="select":

```
<vue-excel-column type="map" field="gender" width="80px" label="Gender" :options="genderOption" />

methods: {
   async genderOption () {
      return axios.post('getGenderList').then(res => res.data)
   }
