### ISSUE TITLE
Edit selected data

### ISSUE THREAD

**Issue by unerp** [cscan/vue3-excel-editor#12]
When data is modified, the selected data is also changed

    <vue-excel-editor 
        ref="exGrid" 
        v-model="jsondata" 
        height="300px" 
        @select="gridSelect" 
        @update="gridUpdate"
      >
        <vue-excel-column field="user"   label="User ID"       type="string" width="150px" />
        <vue-excel-column field="name"   label="Name"          type="string" width="150px" />
        <vue-excel-column field="phone"  label="Contact"       type="string" width="150px" />
        <vue-excel-column field="gender" label="Gender"        type="select" width="100px" :options="['F','M','U']" />
        <vue-excel-column field="age"    label="Age"           type="number" width="100px" />
        <vue-excel-column field="birth"  label="Date Of Birth" type="date"   width="150px" />
    </vue-excel-editor>

![image](https://user-images.githubusercontent.com/12321739/206113685-847a1721-8665-43e1-a20c-0eb15a8cf8f8.png)

![image](https://user-images.githubusercontent.com/12321739/206113722-99407ed6-90d1-42ae-baed-cce181db93c8.png)

![image](https://user-images.githubusercontent.com/12321739/206113752-4bc1e16a-04df-4140-bc17-d21cce912ab3.png)

**Comment by cscan** [comment]
Yes, this is a special feature, not a bug. I will think how to disable this feature by flag.

**Comment by cscan** [comment]
Added no-mass-update prop at version 1.0.50
