### ISSUE TITLE
add or remove record

### ISSUE THREAD

**Issue by bellpetchpol** [cscan/vue3-excel-editor#14]
```
let rec = {
        id: 1,
        headerId: 1,
        itemNumber: 1,
        description: "description",
 }
this.jsondata.splice(0, 0, rec);
```

I try modified v-model data on runtime but it won't effect the grid both appending or removing

I also try $refs.newRecord and $ref.deleteRecords(0) both won't work either

I need to use v-if on the component then switch it's visibility to make it work like this

```
this.shouldShowDataGrid = false;
await setTimeout(async () => {
        this.shouldShowDataGrid = true;
}, 10);
```

**Comment by cscan** [comment]
Post your data section, I suspect your data defined wrongly

**Comment by bellpetchpol** [comment]
Here my codesandbox 
https://codesandbox.io/s/vue3-excel-editor-data-not-reactive-vf9iou

you should select any cell and then try to press the add or remove button
you will see that actual data is change not the data grid.

It seem when I manipulate jsondata it won't generate the $id field

**Comment by bellpetchpol** [comment]
Hello cscan
I found temporary solution
Here
```
addRow(){

      let rec = {
          user: "kl",
          name: "Kenny Linus",
          phone: "1-891-2345685",
          gender: "M",
          age: 29,
          birth: "1990-09-01",
        };
      this.jsondata.splice(this.currentRowPos + 1, 0, rec);
      let newJsonData = this.jsondata;
      this.jsondata = [...newJsonData];
    }
```
**let newJsonData = this.jsondata;
this.jsondata = [...newJsonData];**
      
I just need to reiterate jsondata
then the $id property will get generate
