### ISSUE TITLE
Add delete row column

### ISSUE THREAD

**Issue by ryhn** [cscan/vue3-excel-editor#2]
For deleting row, can you add "show-delete-col" property with confirm options

**Comment by cscan** [comment]
Sorry, I can't catch your meaning. Could you add more words to describe?

**Comment by ryhn** [comment]
Ok, add :show-delete-col="true" and add the column after row order column, append a clickable delete button or icon for deleting row in column content

If button adding feature could be provided, it might not be needed. But adding this feature much easy to handle deleting row

**Comment by cscan** [comment]
Ok, the component does not provide UI for handling these, but you could add/delete columns by accessing the variable "fields"

**Comment by ryhn** [comment]
How is this possible while the library can not allow html or button field :smiley: I think the topic is not understood by you
