### ISSUE TITLE
下拉表格能够支持吗

### ISSUE THREAD

**Issue by tzwhyqq** [cscan/vue3-excel-editor#25]
我看现在内置的有select datatime  等，我们项目里面有需要 有个 下拉表格。 类似 aggird 和 hansontable 里面的 下拉表格。
1、下拉表格支持的功能， 支持上下箭头选择行。
2、支持回车选中当前行，并填充数据到弹出单元格的行内。
3、自定义下拉表格工具栏。
4、其他功能同当前table。

**Comment by cscan** [comment]
type="select" or type="map"?

**Comment by tzwhyqq** [comment]
我看了下select 跟map不是我想要的效果。可以看看这个 https://hgdtest.oss-cn-hangzhou.aliyuncs.com/test/video/%E7%A4%BA%E4%BE%8B.mp4

**Comment by cscan** [comment]
暫時不支持
