### ISSUE TITLE
inputSquare遮挡了cell，导致hover cell时没法显示errMsg

### ISSUE THREAD

**Issue by TheXiong** [cscan/vue3-excel-editor#28]

**Comment by cscan** [comment]
Could you show me a screenshot?

**Comment by TheXiong** [comment]
没有选中格子时，hover可以看到错误
![image](https://github.com/cscan/vue3-excel-editor/assets/43661809/129c50ed-fb54-4493-848b-3df0778edac4)
选中时，hover没有任何效果
![image](https://github.com/cscan/vue3-excel-editor/assets/43661809/fa816d5b-b4dd-4047-bcab-b377cbbaf0e6)

**Comment by cscan** [comment]
專登的 :p

**Comment by TheXiong** [comment]
> 專登隱藏的，因它會遮檔了一些東西 :p

ok, 那有方法可以实现我这种效果吗？
