### ISSUE TITLE
Custom Search does not work in VUE3

### ISSUE THREAD

**Issue by mvraghavi** [cscan/vue3-excel-editor#29]
![Screenshot 2023-07-06 at 1 14 02 PM](https://github.com/cscan/vue3-excel-editor/assets/138818484/178bc0b1-923f-4e49-a895-9025d12198b2)

**Comment by cscan** [comment]
Yes, it should be fixed in v1.0.21. Thanks.

**Comment by mvraghavi** [comment]
Thank you!

**Comment by KirillD-33** [comment]
Hello! I have this problem now. version1.0.40

**Comment by KirillD-33** [comment]
Hello! I have this problem now. (v1.0.40)
