### ISSUE TITLE
Allow html in cell

### ISSUE THREAD

**Issue by ryhn** [cscan/vue3-excel-editor#3]
Allow html in cell via :html props

**Comment by cscan** [comment]
Hm ... let me think about it. Not straight forward as it is a textbox instead of html

**Comment by ryhn** [comment]
Not required while editing. Object value can contain html.  I'm assuming this library will be used as a datatable, not entirely in excel like table. Actualy some feature can be disabled with prop. In the other issues I opened, actually because of this.

For example; 
- ctrl+A select all row
- clicking the first column to select the row.
- right click on header shows modal search window

**Comment by cscan** [comment]
ctrl+A select all row <- It works
clicking the first column to select the row. <- First column is selectable
right click on header shows modal search window <- Right click the upper-left block will show modal search window

**Comment by ryhn** [comment]
we have communication problem :smile:
