### ISSUE TITLE
Could not find a declaration file for module 'vue3-excel-editor'. 

### ISSUE THREAD

**Issue by kopiaman** [cscan/vue3-excel-editor#33]
Hi could you provide declaration file because i am using vue3 with typescript

**Comment by cscan** [comment]
Sorry, I have no idea about typescript

**Comment by nlubello** [comment]
Hi,
I've the same issue with my typescript project, how did you fixed? @kopiaman

**Comment by cscan** [comment]
Anyone can help to port this into typescript?

**Comment by atima** [comment]
I manage to fix the warning by adding the file `vue3-excel-editor.d.ts` to the project with the following content:

`declare module 'vue3-excel-editor'`

Ref: https://stackoverflow.com/questions/44056256/typescript-how-to-bind-type-declaration-to-import-statement
