### ISSUE TITLE
Nested json

### ISSUE THREAD

**Issue by samgevorgyan** [cscan/vue3-excel-editor#36]
Hi
Could you please explain how can I use nested JSON as a column header field?

for example 
```
{
...
car:[{car1: red},{car2: blue}]
....
}
 <vue-excel-column field="car[0].car1">
 <vue-excel-column field="car[1].car2">
```
 
 Thank you

**Comment by cscan** [comment]
You do not need to define the vue-excel-column tags, the component will
create according to the JSON.
