### ISSUE TITLE
Grid is not refreshing when rows are deleted.

### ISSUE THREAD

**Issue by seagulledge** [cscan/vue3-excel-editor#37]
I am using Vue3 composition API, and I made a button handler to delete selected records.   The action partially works.  The record(s) are removed from the data model, the 'delete' event is called, and exporting the data afterwards does not include the deleted rows.   

However:  the rows are NOT visually removed from the table.  They still appear, and can be selected and edited.   No changes are tracked on those edits, and the records can't be deleted again.   Tested with just deleteRecord() and had the same problem.
```
   const grid = ref<any>(null)
   
   const DeleteRecord = () => {
        grid.value.deleteSelectedRecords()
    }
```

**Comment by cscan** [comment]
You may need to declare the variable in data region in Vue
