### ISSUE TITLE
Background Color

### ISSUE THREAD

**Issue by Jmuzu** [cscan/vue3-excel-editor#41]
How can i change the background color of this? trying using tailwind css class but doesn't work only text colors

**Comment by cscan** [comment]
Did you try cellStyle( )?

**Comment by Jmuzu** [comment]
Not yet is there an example how to do it? I can't see it in the docs. thank you.

**Comment by RonchettiAssociati** [comment]
This works for me.

In the template:

`<vue-excel-editor v-if="!tokenHasOptions" class="editor"
          :cell-style="cellStyle"
          >`

and then in methods:

`cellStyle (content) {
      var cellStyleObject = {
        'font-size': '24px',
        'text-align': 'center',
        'color': 'black'
      }
return cellStyleObject;
  }
  `

**Comment by Jmuzu** [comment]
Will try it thank you!
