### ISSUE TITLE
DOUBT: not able to use this.$refs.grid, when using new <script setup> instead of <script>

### ISSUE THREAD

**Issue by chandakash** [cscan/vue3-excel-editor#42]
https://vuejs.org/api/sfc-script-setup.html
i'm using this new approach, but now how do I access the grid.

**Comment by cscan** [comment]
I am sure $refs is only created after mounted. For vue, if you not familiar with composition API, please use the classic option API

**Comment by chandakash** [comment]
Cool thank you!
