### ISSUE TITLE
Can I just modify the background color of a row

### ISSUE THREAD

**Issue by hkuzxc** [cscan/vue3-excel-editor#47]

**Comment by hkuzxc** [comment]
Btw may I ask how validate works after I update the data?

**Comment by unpseudocomplique** [comment]
Yea this would be cool, i was thinking about using this cool lib for excel import. 

It's an important topic to validate all fields are good. maybe the best way would be to be able to set style on the cell / row when a cell is not valid?

**Comment by cscan** [comment]
you may add :validate="..." in vue-excel-column
