### ISSUE TITLE
virtual scrolling on mobile

### ISSUE THREAD

**Issue by samgevorgyan** [cscan/vue3-excel-editor#50]
Hello,

It is not possible to scroll down when using the phone. The horizontal scroll works perfectly (via finger touch), but the same functionality does not work for virtual scrolling.

**Comment by samgevorgyan** [comment]
![chrome_0pG4mipdrJ](https://github.com/cscan/vue3-excel-editor/assets/19644256/5e7fa8c1-ac2e-4242-a095-7003ec6d21d2)

**Comment by cscan** [comment]
The vertical scrolling of the component is by coding by default. If you want to make it works in mobile, you may try disable the paging, and also try to set the exact height of the grid. Please left comment after you tested.
