### ISSUE TITLE
the height does not match to 100% of the parent

### ISSUE THREAD

**Issue by ptcgh** [cscan/vue3-excel-editor#53]
when i input too many data , will appear a scroller out the vue3-excel-editor. 

![image](https://github.com/cscan/vue3-excel-editor/assets/16915939/67217fae-1859-4d84-857b-27c6a3ecdba2)
![image](https://github.com/cscan/vue3-excel-editor/assets/16915939/5e761888-02e5-4d77-bea6-ba5ade21056e)

**Comment by cscan** [comment]
Maybe due to the missing filter row.

**Comment by cscan** [comment]
What is the result after adding the filter col, does it fix the issue?
