### ISSUE TITLE
keep give non-stop warnings [Vue warn]: Wrong type passed as event handler to onColspan - did you forget @ or : in front of your prop?

### ISSUE THREAD

**Issue by gravin** [cscan/vue3-excel-editor#54]
it keeps give below warnings when created.

chunk-R5FCYZP3.js?v=59b443b7:1512 [Vue warn]: Wrong type passed as event handler to onColspan - did you forget @ or : in front of your prop?
Expected function or array of functions, received type number. 
  at <VueExcelFilter ref_for=true ref="filter-index" colspan=1  ... > 
  at <VueExcelEditor ref_for=true ref="grid" modelValue= (8) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]  ... > 
  at <ElTabPane key="rege_project_file" label="rege_project_file" name="rege_project_file" > 
  at <ElTabs modelValue="rege_project_file" onUpdate:modelValue=fn class="demo-tabs"  ... > 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {__v_skip: true} > > 
  at <RouterView> 
  at <ElMain> 
  at <ElContainer> 
  at <ElContainer> 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {__v_skip: true} > > 
  at <RouterView> 
  at <App>

**Comment by nima-nejad** [comment]
could you find a solution for it?

**Comment by cscan** [comment]
Hi all, it is fixed at version 1.0.40
