### ISSUE TITLE
Component is not rendering for me

### ISSUE THREAD

**Issue by Ngsnet** [cscan/vue3-excel-editor#58]
Hi, 

i am starting with vue3 and excel editor, i have very simple example and after running it  and i get this console warning and component does not render :

> 
>  [Vue warn]: Component is missing template or render function:  {install: ƒ} 
>   at <Anonymous modelValue= (5) [{…}, {…}, {…}, {…}, {…}] onUpdate:modelValue=fn width=400  ... > 
>   at <App>
> 

I am not able to find out how to render component. I am using vue3 compositionApi, vite, xslx , this versions :

>     "vue": "^3.4.21",
>     "vue3-excel-editor": "^1.0.45",
>     "xlsx": "^0.18.5"
i am using the most simple version of component to render inside template
```
.....
<Vue3ExcelEditor v-model="jsondata" :width="400" :height="200"> </Vue3ExcelEditor>
.....
```
I cannnot find out , what i am doing wrong, any help is welcome.

Denis

**Comment by cscan** [comment]
The tag should be <VueExcelEditor ...> or <vue-excel-editor .... >
