### ISSUE TITLE
When autoFillWidth is set to true, the cell will automatically increase in width infinitely

### ISSUE THREAD

**Issue by StrongerLph** [cscan/vue3-excel-editor#59]
code ：
![image](https://github.com/user-attachments/assets/811c6522-18bf-4a5f-a349-bc4e75e8411c)

display:

![demo](https://github.com/user-attachments/assets/5c56f899-0eae-4f7e-ba3e-438961a823cc)

what happen? who can help me? I need `autoFillWidth`

**Comment by cscan** [comment]
It seems the component continuous receive the window resize event, please verify

**Comment by StrongerLph** [comment]
> It seems the component continuous receive the window resize event, please verify

It looks like the winResize function is running indefinitely,But the `window.innerHeight, window.innerWidth` hasn't actually changed,
![image](https://github.com/user-attachments/assets/9263ad4f-d951-4099-b2bb-0fbd78532138)

**Comment by StrongerLph** [comment]
> It seems the component continuous receive the window resize event, please verify

Breakpoint debugging found that winResize was triggered indefinitely

![image](https://github.com/user-attachments/assets/5f1f2e55-459d-4407-806c-0bd95a0f6a34)

**Comment by cscan** [comment]
Sorry, I could not replicate your problem.

**Comment by StrongerLph** [comment]
> Please remove the width style from vue-excel-editor, and specified width in px for each column, i.e. width="10px" and retry
If I do this, the width of each column is fixed, and when I dynamically change the number of columns displayed, the other columns cannot adapt to the remaining width. That's all I can do for now, but is it a bug

**Comment by StrongerLph** [comment]
> Please remove the width style from vue-excel-editor, and specified width in px for each column, i.e. width="10px" and retry

oh,I think I know how to solve this problem, set a fixed width for the container, make sure that winResize does not trigger.
Thanks for you reply!
