### ISSUE TITLE
Validate all cells on table mount

### ISSUE THREAD

**Issue by CageThrottleUs** [cscan/vue3-excel-editor#60]
I have a specific use-case, which includes validating each cell of the table, as soon as the data is loaded:

1. A user uploads a json file to my Vue app
2. The table is mounted and the content of the json file is loaded into the table using v-model
3. Since the json file is user-created and does probably not match some validation criteria yet, I want to validate all cells as soon as the table-data is loaded and display the error messages (using the error-tooltip of the table) directly to the user (for each cell).

Is it already possible to archive this using the current functionality of the component (an example would be appreciated), or does it need some new implementation?
Thanks for the great component, really appreciate the work behind this project.

**Comment by cscan** [comment]
Since it involves row validation and cell validation. I suggest you trigger an update of each cell, by calling this.$refs.editor.updateCell( rowPos, name, content ). Here is some codes for your references:

```js
tableData.forEach((row, pos) => {
   Object.keys(row).forEach(name => this.$refs.editor.updateCell(pos, name, row[name]))
})
```

The above code has not been tested, but it contains the all what you need
